### ISSUE TITLE
Role assignment name must be a guid?

### ISSUE THREAD

**Issue by fabiomilheiro** [pulumi/pulumi-azure-nextgen#194] opened 2020-12-30 21:26 UTC
I need to create some role assignments. In this specific case, I need to allow a group to be able to have have "owner" access to some very specific resource.

Here's what I tried:

```csharp
using Pulumi.AzureNextGen.Authorization.V20200401Preview;

var name = $"{@namespace.GetResourceName()}-{this.PrincipalName}-RoleAssignment".RemoveSpaces();
            
            new RoleAssignment(
                name,
                new RoleAssignmentArgs
                {
                    RoleAssignmentName = name,
                    RoleDefinitionId =
                        RoleDefinitionService.Get("Azure Service Bus Data Owner")
                           .Apply(rd => rd.RoleDefinitionId),
                    Scope = @namespace.Id,
                    PrincipalType = this.PrincipalType,
                    PrincipalId = this.PrincipalId
                });
```

But it fails with the following message:
status code 400
```json
{
  "error": {
    "code":"InvalidRoleAssignmentId",
    "message":"The role assignment ID 'AAAA-RoleAssignment' is not valid. *****The role assignment ID must be a GUID*****."
  }
}
```

However, none of the `RoleAssignmentArgs` properties refers to the *role assignment id* explicitly but I found out it's the `RoleAssignmentName`.

If I change the above code to use a guid for the `RoleAssignmentName`, then it works:

```csharp
new RoleAssignment(
                name,
                new RoleAssignmentArgs
                {
                    RoleAssignmentName = Guid.NewGuid().ToString(), // <== change here
                    RoleDefinitionId =
                        RoleDefinitionService.Get("Azure Service Bus Data Owner")
                           .Apply(rd => rd.RoleDefinitionId),
                    Scope = @namespace.Id,
                    PrincipalType = this.PrincipalType,
                    PrincipalId = this.PrincipalId
                });
```

Even though it's working, I'm not very happy about it because Pulumi will be re-creating the assignment every single time we run `pulumi up`.

Is there a more elegant way to create the role assignments?

**Comment by fabiomilheiro** [comment] 2020-12-30 21:56
I've been searching around and `RoleAssignmentName` above is required. Can we make it not required?

I went back to use the `Pulumi.Azure.Authorize` namespace which, in this case, seems like a better fit.

```cshar
new Assignment(
                name,
                new AssignmentArgs
                {
                    // Name = name, 
                    // ^^^ Same as the RoleAssignmentName but it's not required
                    // so the ID is generated and kept the same on subsequent runs.
                    RoleDefinitionName = "Azure Service Bus Data Owner",
                    Scope = @namespace.Id,
                    PrincipalId = this.PrincipalId
                });
```

I'm still interested in finding out the best way of creating role assignments. Any other ideas?

**Comment by mikhailshilkov** [comment] 2020-12-30 22:39
Dupe of https://github.com/pulumi/pulumi-azure-nextgen/issues/113

You can use a `RandomUuid` resource from `Pulumi.Random` for stable GUIDs. FWIW, that's how the Azure API is modeled.

**Closed** 2020-12-31 10:04 UTC
