### ISSUE TITLE
Feature request: Debugging log with all REST API calls

### ISSUE THREAD

**Issue by UnoSD** [pulumi/pulumi-azure-nextgen#272] opened 2021-02-07 18:57 UTC
Would be nice to have a logging configurable feature to output all the REST API calls to Azure to debug issues.

One use case example could be this one: https://github.com/pulumi/pulumi-azure-nextgen/issues/271

I am also getting a 500 InternalServerError when updating a Function App and Pulumi does not provide any more details. Would be really helpful to know the URL and the body of the update request so I could figure out if it is a valid request and if the issue is with Azure or Pulumi before opening an issue. Currently, the only option is to set up Fiddler and intercept HTTPS traffic.

Thank you

**Comment by mikhailshilkov** [comment] 2021-02-07 19:05
You can get HTTP debug logs with `pulumi up -v=9 --logtostderr --logflow --debug` (requires a recent version of the provider)

**Comment by mikhailshilkov** [comment] 2021-02-07 19:06
Dupe of #177

**Closed by mikhailshilkov** 2021-02-07 19:06 UTC
