### ISSUE TITLE
How to get the storage account connection string using NextGen?

### ISSUE THREAD

**Issue by fabiomilheiro** [pulumi/pulumi-azure-nextgen#192] opened 2020-12-30 14:31 UTC
Using `Pulumi.Azure`, I used to create a storage account and could access the connection string e.g.:

```csharp
var connectionString = newStorageAccount.PrimaryConnectionString;
```

I'm trying to convert code to `Pulumi.Azure.NextGen` but cannot find a way to get the connection string.

The Pulumi website mentions somewhere we have exposure to everything but I wonder now what I'm missing to get access to the connection string.

Can anyone help please?

By the way, if it helps, what I'm really trying to achieve is to get the connection string into the key vault (not yet prepared for password-less authentication).

**Comment by fabiomilheiro** [comment] 2020-12-30 14:46
Please let me know if there's a better solution but, in the meantime, I got a way to sort it by using the `Pulumi.Azure` library to get the connection string:

```csharp
var connectionString = Output.Tuple(storageAccount.Name, resourceGroup.Name)
               .Apply(
                    items =>
                    {
                        var (storageAccountName, resourceGroupName) = items;

                        return Output.Create(
                            GetAccount.InvokeAsync(
                                new GetAccountArgs
                                {
                                    Name = storageAccountName,
                                    ResourceGroupName = resourceGroupName
                                }))
                           .Apply(account => account.PrimaryBlobConnectionString);
                    });
```

**Comment by mikhailshilkov** [comment] 2020-12-30 15:28
Our templates have an example of that: https://github.com/pulumi/templates/blob/744f2d32eee0021558baf44536763fb27c63bc6d/azure-nextgen-csharp/MyStack.cs#L32-L47

**Comment by mikhailshilkov** [comment] 2020-12-30 15:36
Azure APIs don't return sensitive information by default, so you'd have to make an explicit call to `ListStorageAccountKeys` to get the connection string.

Here is a full example:

```cs
using System.Threading.Tasks;
using Pulumi;
using Pulumi.AzureNextGen.Resources.Latest;
using Pulumi.AzureNextGen.Storage.Latest;
using Pulumi.AzureNextGen.Storage.Latest.Inputs;

class MyStack : Stack
{
    public MyStack()
    {
        // Create an Azure Resource Group
        var resourceGroup = new ResourceGroup("resourceGroup", new ResourceGroupArgs
        {
            ResourceGroupName = "my-rg",
            Location = "WestUS"
        });

        var storageAccount = new StorageAccount("sa", new StorageAccountArgs
        {
            ResourceGroupName = resourceGroup.Name,
            AccountName = "mystorageaccount",
            Location = resourceGroup.Location,
            Sku = new SkuArgs
            {
                Name = SkuName.Standard_LRS
            },
            Kind = Kind.StorageV2
        });

        var connectionString = Output.Tuple(resourceGroup.Name, storageAccount.Name).Apply(names =>
            Output.CreateSecret(GetStorageAccountPrimaryConnectionString(names.Item1, names.Item2)));
        
        // ...
    }

    private static async Task<string> GetStorageAccountPrimaryConnectionString(string resourceGroupName, string accountName)
    {
        var accountKeys = await ListStorageAccountKeys.InvokeAsync(new ListStorageAccountKeysArgs
        {
            ResourceGroupName = resourceGroupName,
            AccountName = accountName
        });
        return $"DefaultEndpointsProtocol=https;AccountName={accountName};AccountKey={accountKeys.Keys[0].Value}";
    }
}
```

**Comment by mikhailshilkov** [comment] 2020-12-30 15:37
Dupe of #140

**Comment by mikhailshilkov** [comment] 2020-12-30 20:51
I'll go ahead and close this. Let me know if I can help further.

**Closed by mikhailshilkov** 2020-12-30 20:51 UTC
Labels: question

**Comment by fabiomilheiro** [comment] 2020-12-30 21:17
That helped a lot. Thanks
